apiVersion: v1
kind: Secret
metadata:
  name: ucsm-acm-secret-env
  namespace: "2023241041"
type: Opaque
data:
  # root en base64 -> cm9vdA==
  surreal-user: cm9vdA==
  
  # root en base64 -> cm9vdA==
  surreal-password: cm9vdA==
  
  # http://db-service:8000/rpc en base64 -> aHR0cDovL2RiLXNlcnZpY2U6ODAwMC9ycGM=
  database-url: aHR0cDovL2RiLXNlcnZpY2U6ODAwMC9ycGM=