apiVersion: v1
kind: Secret
metadata:
  name: ucsm-acm-secret-env
  namespace: "2023241041"
type: Opaque
data:
  # Recuerda: Los valores deben estar codificados en base64
  # arelyxl en base64 -> YXJlbHl4bA==
  postgres-user: YXJlbHl4bA==
  # tu_password_seguro en base64 -> dHVfcGFzc3dvcmRfc2VndXJv
  postgres-password: ZWxtb21lcm8xMjM=
  # postgresql://arelyxl:tu_password_seguro@db-service:5432/acm_db en base64:
  database-url: cG9zdGdyZXNxbDovL2FyZWx5eGw6ZWxtb21lcm8xMjNAZGItc2VydmljZTo1NDMyL3Vjc21fYWNt
